language: R
sudo: required
cache: packages

r_packages:
  - covr

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo add-apt-repository -y ppa:opencpu/jq
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libprotobuf-dev protobuf-compiler libv8-3.14-dev libjq-dev
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libudunits2-dev

after_success:
- Rscript -e 'library(covr); codecov()'
